name: Account Sync  # 工作流名称（必须）

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */6 * * *'  # 每6小时自动运行（可选）

jobs:
  sync:  # 任务ID
    runs-on: ubuntu-latest  # 运行环境（必须）
    
    steps:  # 执行步骤（至少一个）
      - name: Checkout code  # 步骤1：拉取代码
        uses: actions/checkout@v3
        
      - name: Run OCR script  # 步骤2：执行脚本
        run: python ocr.py
